### ISSUE TITLE
During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by Hiroki11x** [RotaPlusPlus/Fitbit_HeartRate_Visualizer#5]
```
Traceback (most recent call last):
  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/indexes/base.py", line 2525, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_it
em
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_it
em
KeyError: -1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_heart_rate.py", line 97, in <module>
    task(client)
  File "get_heart_rate.py", line 79, in task
    print(heart_df[-1])

  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/frame.py", line 2139, in __getitem__
    return self._getitem_column(key)
  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/frame.py", line 2146, in _getitem_column
    return self._get_item_cache(key)
  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/generic.py", line 1842, in _get_item_cache
    values = self._data.get(item)
  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/internals.py", line 3843, in get
    loc = self.items.get_loc(item)
  File "/Users/hirokinaganuma/.pyenv/versions/3.4.3/Python.framework/Versions/3.4/lib/python3.4/site-packages/p
andas/core/indexes/base.py", line 2527, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 117, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_it
em
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_it
em
KeyError: -1
```

**Comment by Hiroki11x** [comment]
```py
# 繰り返すタスク
def task(authd_client, start_time="16:15", end_time="16:40"):
    data_sec = authd_client.intraday_time_series('activities/heart', DATE, detail_level='1sec',start_time=start_time, end_time=end_time) #'1sec', '1min', or '15min'
    heart_sec = data_sec["activities-heart-intraday"]["dataset"]

    heart_df = pd.DataFrame.from_dict(heart_sec)
    heart_df.index = pd.to_datetime([DATE + " " + t for t in heart_df.time])
    heart_df = heart_df.drop("time", axis=1)
    print(heart_df[-2:-1])
```
